### ISSUE TITLE
update "unread" message in dashboard

### ISSUE THREAD

**Issue by pruffier** [Cocolabs-SAS/cocorico#116]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Support request? | yes

hello,
having issues with the message within the admin panel. when reading the message, it does not update my dashboard notification of the unread message. it keeps my "dashboard (1)..."
thank you!

**Comment by cocolabssas** [comment]
Hi,

It means you still have a unread message in the offerer or asker dashboard.  Reading your messages in both dashboards will removed the remaining unread message.

**Comment by pruffier** [comment]
hi,

no, have read from the offerer and asker dashboard and it does not update.

thanks.

**Comment by eshelf** [comment]
Same problem for me. The number of unread messages is not updated after reading the messages.

**Comment by cocolabssas** [comment]
Hi,

It is a problem of Doctrine result cache. We are fixing it.

**Comment by eshelf** [comment]
Hi, thanks for updating us! The issue was closed. How will us know when the bug is fixed?

**Comment by eshelf** [comment]
Hey, guys! Thanks for dealing with this.

I've tried it and I think you guys also need to include the line below in the methods indexAction, deleteAction and newThreadAction.

`$this->get('doctrine')->getManager()->getRepository('CocoricoMessageBundle:Message') ->clearNbUnreadMessageCache($this->getUser()->getId());`

Besides that, in the method nbUnReadMessagesAction, only GET was accepted and it was generating an error. I had to delete it in order to properly function.

I'm sorry for not sending a pull request. As you can see on issue [126](https://github.com/Cocolabs-SAS/cocorico/issues/126), I'm strugling to sincronize my repository with yours.

**Comment by cocolabssas** [comment]
Hi eshelf,

Thanks for your feedback.
The doctrine result cache is now cleared for new and deleted messages (https://github.com/Cocolabs-SAS/cocorico/commit/f55522eaa000721f6ff3ca9ab6be8b1900ac6ed0).

Concerning the `nbUnReadMessagesAction `only the method GET should be used and we have no errors with this method.
