### ISSUE TITLE
Updating repository not branched from master

### ISSUE THREAD

**Issue by eshelf** [Cocolabs-SAS/cocorico#126]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| Support request? | yes

Hi,

I downloaded the entire code, made my customizations and then created a brand new repository, not related to the master of this project in a way that I'm not working on a branch of the Cocorico project. **Please don't judge me, since when I did it 6 months ago, I had no knowledge on the git process.**

Now, I want to take advantage of all of the bug fixes from the last 6 months and I don't know how to do it. I believe I'll have to make a lot of manual and hard work, but I actually don't mind. I just would like to have some guidance on this process.

Can anyone help me giving me an idea of the process to follow?

**Comment by cocolabssas** [comment]
Hi eshelf,

To get last cocorico modifications on your repository you can  apply a patch containing all commits between your last version of cocorico and the last version of cocorico.

Ex:
You downloaded cocorico v0.3.4 and now you want to get all modifications made on cocorico since this release. 
Saying that the last version of cocorico is v0.4.1 you have to apply patch between v0.3.4 and v0.4.1.
Here is the corresponding patch:
https://github.com/Cocolabs-SAS/cocorico/compare/v0.3.4...v0.4.1.patch (you can also generate it by command line).

Download it and rename it to v0.3.4-v0.4.1.patch then apply it on your repository branch: 
If you use PHPStorm you have a contextual menu 'Apply patch' when you right click on this file.
You can also use command line : `git apply v0.3.4-v0.4.1.patch`.

Note that while applying a patch you can have some conflicts to resolve. 
If you have too much conflicts with app/Resources/translations files you can ignore them and then execute `php app/console translation:extract en --config=cocorico`  once the patch is applied.

P.S.:
A method to keep in sync a forked repo with the original one is also explained here:  
https://help.github.com/articles/syncing-a-fork/#platform-linux

Hope that helps

**Comment by eshelf** [comment]
Hey, guys! Thanks for helping! This procedure would work fine!

In order to slice the conflict merges in smaller parts, I decided to follow a similar aproach, applying my patches to your repository as described [here](https://stackoverflow.com/questions/47998717/merging-non-related-git-repositories/48027029#48027029).

Once again, thank you very much for your help!

**Comment by cocolabssas** [comment]
You're welcome :)
