### ISSUE TITLE
Backend Forms

### ISSUE THREAD

**Issue by amaurybrisou** [Cocolabs-SAS/cocorico#14]
Hello, 

I'm creating Forms into my pages and wonder if you have basic mailing actions to bind the form with ?
Do I need to develop my own actions ?

Thank you

**Comment by m-root** [comment]
It depends on what in particular you'd like to bind.                                                                                                                                                                                                                                                                                                                                        Kind RegardsMuema KambaSent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Amaury BrisouSent: Tuesday, 26 July 2016 16:30To: Cocolabs-SAS/cocoricoReply To: Cocolabs-SAS/cocoricoSubject: [Cocolabs-SAS/cocorico] Backend Forms (#14)Hello, 

I'm creating Forms into my pages and wonder if you have basic mailing actions to bind the form with ?
Do I need to develop my own actions ?

Thank you

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by amaurybrisou** [comment]
here the idea is to catch every field name and content to send them by email. just wondering if there are prepared actions  for this purpose

**Comment by cocolabssas** [comment]
There is not this kind of functionality. You can look how mails are send in Cocorico\CoreBundle\Mailer\TwigSwiftMailer and follow the same method.
