### ISSUE TITLE
Got an exception accessing any url

### ISSUE THREAD

**Issue by pcP1r4t3** [Cocolabs-SAS/cocorico#151]
Hi everyone,

I installed cocorico step by step like in the installation guide.
The home page works fine but when i try to open any other url (e.g: /admin, /inscription) an exception is thrown.
![error1](https://user-images.githubusercontent.com/8086846/37294348-ea4b6904-2615-11e8-94fb-bcc8dbcc42c2.png)

The StackTrace:
1- in src/Cocorico/ReviewBundle/Security/Voter/ReviewVoter.php at line 50   -
    public function vote(TokenInterface $token, $booking, array $attributes)
    {
        // check if class of this object is supported by this voter
        if (!$this->supportsClass(get_class($booking))) {
            return VoterInterface::ACCESS_ABSTAIN;
        }
2- at ErrorHandler ->handleError ('2', 'get_class() expects parameter 1 to be object, null given', '/home/snull/dotit/cocorico/src/Cocorico/ReviewBundle/Security/Voter/ReviewVoter.php', '50', array('token' => object(AnonymousToken), 'booking' => null, 'attributes' => array('ROLE_ADMIN'))) 
3- at get_class (null) 
in src/Cocorico/ReviewBundle/Security/Voter/ReviewVoter.php at line 50   + 
4- at ReviewVoter ->vote (object(AnonymousToken), null, array('ROLE_ADMIN')) 
in app/cache/dev/classes.php at line 2870   + 
5- at AccessDecisionManager ->decideUnanimous (object(AnonymousToken), array('ROLE_ADMIN'), null) 
in app/cache/dev/classes.php at line 2797   + 
6- at AccessDecisionManager ->decide (object(AnonymousToken), array('ROLE_ADMIN'), null) 
in app/cache/dev/classes.php at line 2925   + 
7- at AuthorizationChecker ->isGranted (array('ROLE_ADMIN'), null) 
in vendor/symfony/symfony/src/Symfony/Component/Security/Core/SecurityContext.php at line 102   + 
8- at SecurityContext ->isGranted ('ROLE_ADMIN') 
in vendor/sonata-project/user-bundle/Controller/AdminSecurityController.php at line 61   + 
9- at AdminSecurityController ->loginAction () 
10- at call_user_func_array (array(object(AdminSecurityController), 'loginAction'), array()) 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php at line 139   + 
11- at HttpKernel ->handleRaw (object(Request), '1') 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php at line 62   + 
12- at HttpKernel ->handle (object(Request), '1', true) 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php at line 69   + 
13- at ContainerAwareHttpKernel ->handle (object(Request), '1', true) 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php at line 185   + 
14- at Kernel ->handle (object(Request)) 
in web/app_dev.php at line 30   + 
15- at require ('/home/snull/dotit/cocorico/web/app_dev.php') 
in vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Resources/config/router_dev.php at line 40 `
I would to know is this caused by a misconfiguration or it's a problem of the framework itself.
 PS: I cloned the repo today.

Thx for your help.

**Comment by cocolabssas** [comment]
Hello pcP1r4t3,

Your issue seems very strange because the `ReviewVoter `is only used in the `Review newAction` `Cocorico/ReviewBundle/Controller/Dashboard/ReviewController.php:39`.
You can only have this exception when you make a new review in the new review action.

Have you made some changes?
Could you clear your cache?
Could you sign-out then sign-in again?

**Comment by cocolabssas** [comment]
Feel free to reopen if you still have the issue

**Comment by shiv6146** [comment]
@cocolabssas Even I get the same error when trying to visit any url related to login, registration or publish new listing in my local dev environment. Please help. Issue is the same and references are also the same as the above.

**Comment by Pratiklocho** [comment]
@cocolabssas i also get same error while visit any login & register url

**Comment by business-hall** [comment]
The problem could be caused by a newer version of PHP (PHP 7.2.0+) that no longer allows NULL as arg to get_class. 

From http://php.net/manual/en/function.get-class.php.

>Note: Explicitly passing NULL as the object is no longer allowed as of PHP 7.2.0. The parameter is still optional and calling get_class() without a parameter from inside a class will work, but passing NULL now emits an E_WARNING notice.

On the date of this post, the PHP version in the docker build from https://github.com/Cocolabs-SAS/cocorico-docker defaults to:

> $ php -v
PHP 7.2.13 (cli) (built: Dec  7 2018 16:12:01) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.13, Copyright (c) 1999-2018, by Zend Technologies

Calls similar to **$this->container->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_FULLY')**  pass only one parameter, causing the $booking argument to be NULL in src/Cocorico/ReviewBundle/Security/Voter/ReviewVoter.php.

![screenshot from 2018-12-29 16-36-31](https://user-images.githubusercontent.com/45107241/50542639-0e024b80-0b88-11e9-8a49-b2ad9e62f89a.png)

If the PHP version is the problem, the simplest solution is to use an earlier version of PHP.

**Comment by business-hall** [comment]
The problem could be caused by a newer version of PHP (PHP 7.2.0+) that no longer allows NULL as arg to get_class. 

From http://php.net/manual/en/function.get-class.php.

>Note: Explicitly passing NULL as the object is no longer allowed as of PHP 7.2.0. The parameter is still optional and calling get_class() without a parameter from inside a class will work, but passing NULL now emits an E_WARNING notice.

On the date of this post, the PHP version in the docker build from https://github.com/Cocolabs-SAS/cocorico-docker defaults to:

> $ php -v
PHP 7.2.13 (cli) (built: Dec  7 2018 16:12:01) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.13, Copyright (c) 1999-2018, by Zend Technologies

Calls similar to **$this->container->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_FULLY')**  pass only one parameter, causing the $booking argument to be NULL in src/Cocorico/ReviewBundle/Security/Voter/ReviewVoter.php.

![screenshot from 2018-12-29 16-36-31](https://user-images.githubusercontent.com/45107241/50542639-0e024b80-0b88-11e9-8a49-b2ad9e62f89a.png)

If the PHP version is the problem, the simplest solution is to use an earlier version of PHP.
