### ISSUE TITLE
Php version

### ISSUE THREAD

**Issue by jimix974** [Cocolabs-SAS/cocorico#18]
hello,

I'm on ubuntu 16.04
Does cocorico run with php7 ???

Because I can't install 5.4 version

Thanks a lot.
Jimmy

**Comment by SOFRACS** [comment]
We haven't tested it, the tested version is 5.4. If you give it a try can you let us know how that went?

Anthoni

**Comment by phe-sofracs** [comment]
Bonjour,

Suite à un accident domestique Henri Phe sera absent du bureau jusqu'au 31/10/2016. Le reste de l'équipe reprend votre dossier afin d'assurer la continuité de votre production. 

Anthoni Noyon

**Comment by xpeering** [comment]
Hi Jimmy!
Can you answer if you have installed Cocorico on PHP 7?
If yes, how was your experience?
Thanks!

**Comment by xpeering** [comment]
# About Installing Cocorico version 0.3.2 on Ubuntu server 16.04.2 LTS with default PHP 7

Trying to install it, I receive the follow error message:

PHP Fatal error:  Cannot use Symfony\Component\Validator\Constraints\True as True because 'True' is a special class name in /var/www/html/marketing/Symfony/src/Cocorico/CoreBundle/Form/Type/Frontend/ListingNewType.php on line 31

then, the only way to install Cocorico 0.3.2 was doing an PHP downgrade to 5.6 tested version.
for more information about downgrade, please check the link below:
http://askubuntu.com/questions/756181/installing-php-5-6-on-xenial-16-04
