### ISSUE TITLE
Geocoding issues with "Rhône, France"

### ISSUE THREAD

**Issue by Damiano1376** [Cocolabs-SAS/cocorico#200]
| Q                | A
| ---------------- | -----
| Bug report?      | [y]
| Feature request? | [ ]
| Support request? | [ ]

Hi,

there is an issue when the adress is Rhône, France. It gives no results.
If i set cocorico.listing_search_min_result: 1 and type "Lyon", when I have no results it goes to Rhone and then to 1,0,0 and finished in the US.
You can see this even your demo websites.

What can I do to avoid this ?

Thanks

**Comment by cocolabssas** [comment]
Hi,

The problem is that Google Maps API does not returned country for Rhone : https://maps.googleapis.com/maps/api/geocode/json?address=Rh%C3%B4ne,%20France&key=YOURAPIKEY 

You could check the value of parentLocation.address in src/Cocorico/CoreBundle/Resources/views/Frontend/ListingResult/result.html.twig:238
and for example stop the search extending if the value is not correct.

Hope it helps
