### ISSUE TITLE
Payment methods

### ISSUE THREAD

**Issue by giovannix** [Cocolabs-SAS/cocorico#27]
Hello!

How can I set cocorico to accept payment methods like credit card and paypal?

**Comment by SOFRACS** [comment]
Hi giovannix,

You have to set it up according to the payment gateway you're using for your project. Cocorico doesn't offer a specific solution to set it up for you.

**Comment by giovannix** [comment]
Hi SOFRACS.

As an inexperienced user on Symfony, I'm not sure how to install new bundles. For example, I saw that in the src/Cocorico/CoreBundle/Admin/BookingBankWireAdmin.php file there is a reference to CocoricoMangoPayBundle. How to install this bundle? Do I need to change anything in the composer.json file?

**Comment by cocolabssas** [comment]
Hi giovannix,

For now the MangoPay bundle is not available. I suggest you in the meanwhile to implement your own payment bundle.

**Comment by giovannix** [comment]
Hi cocolabssas,

I thought the MangoPay bundle was available because I have seen it in the cocorico demo.

**Comment by cocolabssas** [comment]
Hi giovannix,

The mangopay bundle is not publicly available for now. I suggest you to implement your own solution in the meanwhile.

**Comment by eshelf** [comment]
Hi @giovannix giovannix! 

I see that you were trying to integrate Cocorico with JMS Payment Bundle, also with PayPal. 

Did you succeed? Wich solution did you use? I can't find any bundle compatible with Cocorico. Composer always find an incompatible bundle.

I hope you had success on this! If so, please help me on that.

Thanks in advance,

Gerson

**Comment by giovannix** [comment]
Hi @eshelf .

Unfortunately, I had no success on this. We decided to suspend our project with Cocorico for a while.

Giovanni.

**Comment by La-Meche** [comment]
The Paypal offer is not adapted to the marketplace model in general. In most marketplaces, and particularly in Cocorico, the platform escrows payments and thereby acts as the trusted third party that holds the funds for buyers and sellers until the sale is complete. Paypal does not offer delegated escrowing services which is why most marketplaces in the world use providers such as Adyen (Uber, Etsy), Stripe (Lyft) or Braintree (AirBNB). In most cases I would not recommend using Paypal in Cocorico (and in a marketplace in general).

**Comment by Arichefal** [comment]
Hi,

We have started a projet with cocoricos, but we dont know how integrate Stripe in cocorico...
Do y’all have an answer?
