### ISSUE TITLE
which web hosting are using?

### ISSUE THREAD

**Issue by maxpoon6218** [Cocolabs-SAS/cocorico#278]
Dear all,

I am planning to install cocorico. I read some comments that facing problem of using common web hosting services (Eg: godaddy).  So can you advise which is the best options for me?

Please advise.  Thanks

| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [X ]

**Comment by cocolabssas** [comment]
Hi @maxpoon6218 ,

For now Cocorico is mainly hosted on dedicated and cloud servers.
By making a [search](https://www.google.com/search?q=symfony+web+hosting)  we found this result : https://www.whoishostingthis.com/compare/symfony/ and many others one.
You should confirmed also that MongoDB is available.
We will verify and advise one or more hosting providers for Cocorico as soon as possible.

Hope it helps!

**Comment by maxpoon6218** [comment]
Really thanks for your update and looking forward for your updates.  Thanks again.

**Comment by cupidelarocha** [comment]
better you order VPS than regular hosting

**Comment by biomassives** [comment]
I really like to use zeit.co with its generated lamda functions since it is a more stable, less expensive, and reliable platform or AWS via docker-compose, or (ideally since it's super easy to start new sites and bring new devs onboard heroku.com . We are doing a service via heroku currently with saleor and I'd like to make use of cocorio as well, so I'm looking at which one of these will get out group started most easily

**Comment by biomassives** [comment]
I really like to use zeit.co with its generated lamda functions since it is a more stable, less expensive, and reliable platform or AWS via docker-compose, or (ideally since it's super easy to start new sites and bring new devs onboard heroku.com . We are doing a service via heroku currently with saleor and I'd like to make use of cocorio as well, so I'm looking at which one of these will get out group started most easily

**Comment by biomassives** [comment]
And that the mongo fb component need not be on the same service as the executable symphony code for the site itself

**Comment by cocolabssas** [comment]
Hi @gabilanbrc,

Maybe it is too late but here is how to do it : https://symfony.com/doc/master/bundles/DoctrineMongoDBBundle/installation.html#authentication
