### ISSUE TITLE
Facebook button don't work

### ISSUE THREAD

**Issue by igorcherry** [Cocolabs-SAS/cocorico#363]
| Q                | A
| ---------------- | -----
| Bug report?      | [ X]
| Feature request? | [ ]
| Support request? | [ ]

Hello

The button just not pressing and not try to connect with Facebook, any ideas why ?  

Thanks in advance

**Comment by cocolabssas** [comment]
Hello,

- Did you set your FB access in app/config/parameters.yml

```
cocorico.facebook.app_id: xxx
cocorico.facebook.secret: yyy
```

- Did you follow the FB app configuration as described in Cocorico documentation : https://github.com/Cocolabs-SAS/cocorico/blob/master/doc/services-creation.md#create-your-facebook-login-app

Following this  should fix the connection to the FB API.

But once connected to the API we  identified an issue due to FB API modifications. We will fix it asap. In the meanwhile we suggest to disable FB SSO.

**Comment by wolojonathan** [comment]
For information, I have experienced a similar issue which was due to a JS error when calling the FB.login function, resulting in a message saying that access from http is deprecated by FB.

I guess it can only work when the site is accessed through https

**Comment by igorcherry** [comment]
It's right with httpS the button start to be pressed , but still no result ... So waiting for Fb Api plug in from Cocorico experts
