### ISSUE TITLE
fresh cocorico install issues

### ISSUE THREAD

**Issue by rkhyd** [Cocolabs-SAS/cocorico#388]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [y]

I have done two cocorico installs before and they went very smooth. However, with the new version there have been lot of problems. I have installed fresh cocorico and this is the result.
![image](https://user-images.githubusercontent.com/15903310/56036554-c1afd580-5d4a-11e9-80b5-905a5babe9ac.png)
Apache error log reads ` PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 536870920 bytes) in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Intl/Data/Bundle/Reader/BundleEntryReader.php on line 134`
memory_limit is set to -1 in php.ini file
And cocorico on first run loads extremely slowly.
Please advice me on how to fix the above two issues.
Thanks
Ravi Kumar

**Comment by cocolabssas** [comment]
Hi @rkhyd 

we don't have these issues on our side and since SF 3.4 upgrade Cocorico is very more speed. 
Maybe you missed to set correctly something.
Could you give more informations :
- What is your version of Cocorico (commit number).
- What does return this command `sh ./bin/init-db php --env=dev` **Take care it will initialize your DB data**
- What does return this command `sh./bin/init-mongodb php --env=dev` **Take care it will initialize your MongoDB data**
- What are errors in your var/log/dev-yyy-mm-dd.log?

**Comment by cocolabssas** [comment]
Feel free to reopen it if issue persists

**Comment by cocolabssas** [comment]
Hi,

It seems there is a solution to the related  slowness issue here https://github.com/Cocolabs-SAS/cocorico/issues/389

**Comment by rkhyd** [comment]
hi @cocolabssas 
I tried the install again on a new server, and the result is the same as above where i can see two menus and the internal server error at the bottom. 
This happens when we try to use prod instead of dev in these steps

`php bin/console cache:clear --env=prod
mv web/.htaccess.prod.dist web/.htaccess
chmod 744 bin/init-db && ./bin/init-db php --env=prod
chmod 744 bin/init-mongodb && ./bin/init-mongodb php --env=prod
php bin/console assets:install --symlink web --env=prod 
php bin/console assetic:dump --env=prod`

Can you please test it and confirm this as a bug.. thank you.
