### ISSUE TITLE
Bookmark multiple countries

### ISSUE THREAD

**Issue by gonzasylv** [Cocolabs-SAS/cocorico#444]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [ x ]

hi @cocolabssas ,

I try to put several countries in favorites when searching or selecting when adding an ad but the country field disappears when I define only one country.

http://imgur.com/46W6kAbl.png

In my parameters.yml:

    cocorico.listing_countries: []
    cocorico.listing_favorite_countries :
    - FR

I would like to define France, Morocco and Tunisia and that the field "country" remains visible

Thanks you :)

**Comment by cocolabssas** [comment]
Hi @gonzasylv,

It seems that you have modified something because this issue does not exists in Cocorico. 
Could you inspect the element in your browser and see if it exists or if it is hidden. 

You can add for example:

```
cocorico.listing_favorite_countries:
    - FR
    - GB
```
And you will see France and UK in you country select list. 
Try to make a fresh install and you will see that it works.

**Comment by gonzasylv** [comment]
hello @cocolabssas ,
thank you it works for the list of countries against my field is displayed in mobile version and on PC it disappears, I do not understand : 

http://imgur.com/oTDnOXkl.png
