### ISSUE TITLE
I would like to try the demo Coco Docto

### ISSUE THREAD

**Issue by nlesueur** [Cocolabs-SAS/cocorico#466]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [X]

Hello, 

I have build and run the code but I think the default version is light compare to the demos. 
Is it possible to explore the demo code of Coco Docto ?

Many Thanks for your support, 
Nicolas

**Comment by cocolabssas** [comment]
Hi @nlesueur,

The Cocodocto is a demo of the Cocorico Enterprise Edition which code is not public.

**Comment by bsperryn** [comment]
Hi @cocolabssas Could you tell me what the difference is between the public and enterprise editions?

**Comment by rubberduckyint** [comment]
I spoke with cocolabs a while back.  The open source version does not have all the features of the enterprise.  Like it only has one payment gateway and missing other things but its free.  They should really have the open source demo link from git and not link to the enterprise version.  A bit misleading on what you get.

**Comment by rubberduckyint** [comment]
I think it is very misleading that you have a link on Git as the "demo" for the open-source version that goes to the paid enterprise version.  We downloaded and spent a lot of time getting this running under the impression that the doctor demo and its features are part of the public version since it was linked to from Git.  However, that is not true.  The public version is missing half of the features such as keyword search and pretty much most of the admin and many other things.  Please provide a link to a demo of what the public version really is.

**Comment by bsperryn** [comment]
@rubberduckyint Agreed. Thanks to you I didn't invest too much time on this before realising its actually a paid for product in disguise...
