### ISSUE TITLE
Translation not working

### ISSUE THREAD

**Issue by srunzu15** [Cocolabs-SAS/cocorico#498]
| Q                | A
| ---------------- | -----
| Bug report?      | [ ]
| Feature request? | [ ]
| Support request? | [X]

Hi, my problem is that I think at some point the translation is failing and I don't know if it's an API problem or where it might come from.

For example it fails in this case.

![image](https://user-images.githubusercontent.com/29062667/86452036-ff1bcc80-bd1b-11ea-939f-f943c39185fc.png)

And it throws the following error.

![image](https://user-images.githubusercontent.com/29062667/86452153-312d2e80-bd1c-11ea-9855-fcd3f92997be.png)

I would be very grateful if you could help me with this mistake, thank you very much.

**Comment by cocolabssas** [comment]
Hi @srunzu15,

Could you look at the response in your browser console or in your var/logs/devxxx.log to precise your error.
I suppose that it is because you don't set  the parameter `cocorico.translator.secret.key` in your `app/config/parameters.yml`.
To get this key you need to follow this  [guide](https://github.com/Cocolabs-SAS/cocorico/blob/master/doc/services-creation.md) section "Create your microsoft Translator account"
