### ISSUE TITLE
NoApiKeys

### ISSUE THREAD

**Issue by gfvh** [Cocolabs-SAS/cocorico#504]
| Support request? | [ yes]

I already opened same ticket but closed it since i thinked i solved it. Turns out not. This has been also troubleshooted with google and they claim same that no APY key is in use. I installed according to installation document. Not docker. Everything works but not google maps. I have entered API-keys in app/config/parameters.yml

cocorico_geo.google_place_api_key: AIzaSyBomj_-***
cocorico_geo.google_place_server_api_key: AIzaSyBomj_-***
cocorico_geo.ipinfodb_api_key: AIzaSyBomj_-***

perhaps google maps has different variable name in conf? if so please tell

This is full error what i get in web browser console

util.js:229 Google Maps JavaScript API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys

js?libraries=places&language=en:78 You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account For more information on authentication and Google Maps JavaScript API services please see: https://developers.google.com/maps/documentation/javascript/get-api-key

**Comment by SchulzWill** [comment]
Hello there.
For 'cocorico_geo.google_place_api_key' and 'cocorico_geo.google_place_server_api_key' you can use the same API key.

In order to generate your own API key, do not forget to follow: 

> To get an API key:
> 
> Go to the Google Cloud Platform Console.
> Click the project drop-down and select or create the project for which you want to add an API key.
> Click the menu button  and select APIs & Services > Credentials.
> On the Credentials page, click Create credentials > API key. 
> The API key created dialog displays your newly created API key.
> Click Close. 
> The new API key is listed on the Credentials page under API keys. 

And after that, you should run the composer again (the only way that worked with me) 
`composer install && php bin/console assets:install --symlink web --env=dev && php bin/console assetic:dump --env=dev && php bin/console doctrine:cache:clear-metadata && rm -rf ./var/cache && rm -rf ./var/logs && php bin/console cocorico:currency:update`
