### ISSUE TITLE
Can you please update your Documentation?

### ISSUE THREAD

**Issue by rakibulinux** [Cocolabs-SAS/cocorico#511]
Hello, dear Cocorico team, Thanks for making this for us. 
I see in doc there is not much clear about install doc on Linux Server. I think for not much clear doc many people are not able to use your application. I think good Documentation will easier to install and maintenance Cocorico and increase your users. My humble request please make good Documentation that can help users to install it easily with Nginx or Apache.
Regards

**Comment by cocolabssas** [comment]
Hi @rakibulinux 

Thanks for this recommendation. From what we know if you are used to install LAMP environments you should not have to much difficulties to install Cocorico. 
It seems that you have some difficulties to install it. Could you communicate what was your issues and eventually also how you fix them. You can also complete the documentation if some information are missing.

Thanks!

**Comment by rakibulinux** [comment]
Hello, @cocolabssas Thanks for the replay. Can we get an Nginx configuration example for Cocorico? I just get here Apache. It will really help us. Also, you have any community for Cocorico?: https://github.com/Cocolabs-SAS/cocorico/blob/master/doc/virtual-hosts.md

**Comment by shiroineechan** [comment]
hello @cocolabssas i have the same issue as him. i used XAMPP and windows to operate it, can you please show me how to install it or make a video so everyone else who have the same problem can watch it.

**Comment by jmspldnl** [comment]
FWIW - I have over 10yrs of LAMP experience and I've also had issues installing this application...

**Comment by skylancr** [comment]
![cocorico Screen2](https://user-images.githubusercontent.com/19416260/95213551-9bf87500-07f7-11eb-97bb-e6b41e236133.png)

Hello!
I can't install it properly too (and yes, I have experience with local servers). I had tried to install it on two different machines, with WAMP and OpenServer.
Still, I get the this welcome page after the installation is over (as it shown on the screenshot, the layout of the page is broken, there is no pictures and styles)

**Comment by cocolabssas** [comment]
Hello everyone,

First of all thank you for your feedback!
Although many people have succeeded without too much difficulty in installing Cocorico, we will, taking into account your requests, make the installation even easier.
  
In the meantime, here are some remarks:
- It is strongly recommended to use a Linux environment rather than Windows. 
- Nginx: We will be committing in the next few days the Nginx config. To wait, you can take inspiration from the config proposed by Symfony: https://symfony.com/doc/3.4/setup/web_server_configuration.html#nginx
- Read [doc/installation-server-linux.md ](https://github.com/Cocolabs-SAS/cocorico/blob/master/doc/installation-server-linux.md )and [doc/installation-application.md](https://github.com/Cocolabs-SAS/cocorico/blob/master/doc/installation-application.md) carefully 
- Installing Cocorico will be facilitated by your knowledge of LAMP. and Symfony

Concerning your issue @skylancr you need, according to your domain,to set these parameters:
```
cocorico.assets_base_urls: 'http://cocorico.local/'
router.request_context.host: cocorico.local
router.request_context.scheme: http
router.request_context.base_url: ''
```
in your `app/config/parameters.yml` and then execute:
```
php bin/console assets:install --symlink web --env=dev
php bin/console assetic:dump  --env=dev
```

See doc / installation-application.md:107

Hope it helps!
