### ISSUE TITLE
listing viewable only for language selected

### ISSUE THREAD

**Issue by fakelefteye** [Cocolabs-SAS/cocorico#56]
Hello,
For example : 
If I create a listing in english it is only displayed for users that select the english language,
if I select the french language I cannot see the listing in english even though I select the correct area where the item is .

I think they should be viewable even if it is not in the correct language ( people can be lazy to translate ).
I if the user select French ( or other language ) doesnt mean he doesnt understand English...

If there a settings in parameters to allow to display any languages other than the one selected?
Or maybe to force user to translate in other languages?

Thank you

**Comment by kroshp** [comment]
Hi,

The problem was that you didn't have the translation service working. 
But good news, we have just released the new translation service based on the new Azure Microsoft API.
Your listings will now be translated in all enabled languages and will be viewable in all selected languages.

In the near future we will also manage the eventuality that the translation service is not active.

**Comment by fakelefteye** [comment]
great thank you it seems to automatically translate with azure
